# https://wallis.dev/blog/composite-github-actions
name: Use External Resources

on: [push]

jobs:
  run-local-action:
    runs-on: ubuntu-latest
    steps:
      # Otherwise the workflow won't be able to find the action
    - name: Checkout This Repo
      uses: actions/checkout@v3
    - name: Run custom action
      # Use the location in the repository (without action.yml)
      uses: ./actions/example-action.yml@main